[pytest]
# Add the 'src' directory to the python path so tests can find your code
pythonpath = src

# Tells pytest where to look for tests
testpaths = tests

# Standard naming conventions for test files and functions
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Optional: Add default execution flags
# -v: verbose output
# -s: allow print statements to show in console
addopts = -v -s

markers =
    performance: tests that measure execution speed (slow)
    unit: Quick test for individual functions and classes